import React,{useState} from 'react';
import {Field,Check} from './ui.jsx';
import {privacyIssues} from '../shared/privacy.js';
export const names={goal:'目标',fact:'配置与事实',decision:'决定',attempt:'尝试与错误',constraint:'要求',state:'进度',task:'任务'};
export default function MemoryForm({onSave,busy,records,initial,seed={}}){
 const [f,set]=useState({kind:initial?.kind||seed.kind||'fact',title:initial?.claim||seed.title||'',detail:'',source:'',conditions:'',applicabilityKind:initial?.scope?.applicability?.kind||'unknown',applicabilityTask:initial?.scope?.applicability?.task||'',result:'',mistake:'',reason:'',next:'',stage:'in_progress',outcome:'unknown',checked:false,confirmed:false,reviewed:false,redacted:false,inference:false,checkNote:'',recorderKind:'human',recorderName:'',sourceKind:'human',sourceName:'',checkerKind:'human',checkerName:'',replaces:initial?.id||'',changeReason:'',subject_id:initial?.data?.subject_id||seed.subject_id||''});
 const value=(key,extra={})=>({value:f[key]??'',onChange:e=>set({...f,[key]:e.target.value}),...extra});
 const check=key=>({checked:!!f[key],onChange:e=>set({...f,[key]:e.target.checked})});
 const issues=privacyIssues(f);
 return <form onSubmit={e=>{e.preventDefault();onSave({...f,...(['decision','constraint'].includes(f.kind)?{applicability:{kind:f.applicabilityKind,...(f.applicabilityKind==='task'?{task:f.applicabilityTask,...(initial?.scope?.applicability?.task_id&&f.applicabilityTask===initial.scope.applicability.task?{task_id:initial.scope.applicability.task_id}:{})}:{})}}:{}),recorder:{kind:f.recorderKind,id:f.recorderKind==='human'?'local-user':f.recorderName},speaker:{kind:f.sourceKind,id:f.sourceKind==='human'?'local-user':f.sourceName},...(f.checked?{checker:{kind:f.checkerKind,id:f.checkerKind==='human'?'local-user':f.checkerName}}:{})});}}>
  {initial&&<><p className="notice">原记录：{initial.claim}。修订会保留旧版本；新要求不表示功能已经实现。</p><Field label="为什么修改"><textarea required maxLength={2000} placeholder="例如：需要在手机上使用，所以增加触屏操作" {...value('changeReason')}/></Field>{initial.approval&&['constraint','decision'].includes(initial.kind)&&<p className="notice">原要求已有确认。替代它需要提供新的用户原话，并明确确认；AI 建议请作为独立新记录保存。</p>}</>}
  <div className="two"><Field label="记忆类型"><select {...value('kind')} disabled={!!initial}>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="标题"><input autoFocus required maxLength={160} placeholder="用一句话说明这条记忆" {...value('title')}/></Field></div>
  <div className="two"><Field label="谁整理了这条记忆"><select {...value('recorderKind')}><option value="human">用户</option><option value="agent">AI</option><option value="tool">工具</option></select></Field>{f.recorderKind!=='human'&&<Field label="整理者名称"><input required placeholder="例如 Codex" {...value('recorderName')}/></Field>}</div>
  <Field label="内容"><textarea required rows={3} placeholder="只记录你知道的，不确定的部分请说明" {...value('detail')}/></Field>
  {['decision','constraint'].includes(f.kind)&&<><Field label="这条要求适用多久"><select {...value('applicabilityKind')} onChange={e=>set({...f,applicabilityKind:e.target.value,confirmed:false,reviewed:false})}><option value="unknown">尚不明确，保留待核对</option><option value="task">仅指定任务</option><option value="project">项目长期适用</option></select></Field>{f.applicabilityKind==='task'&&<Field label="仅适用于哪个任务"><input required maxLength={300} placeholder="例如：这次只检查手机操作，不改代码" {...value('applicabilityTask')} onChange={e=>set({...f,applicabilityTask:e.target.value,confirmed:false,reviewed:false})}/></Field>}<p className="muted">仅本次的安排不会自动延续到新任务；长期适用也不代表已核验或验收。</p></>}
  {f.kind==='decision' &&<Field label="为什么这样选择"><textarea rows={2} {...value('reason')}/></Field>}
  {['attempt','constraint'].includes(f.kind)&&<Field label="当时环境 / 适用条件"><input required {...value('conditions')}/></Field>}
  {f.kind==='attempt'&&<><div className="two"><Field label="结果"><select {...value('outcome')}><option value="unknown">尚不确定</option><option value="failed">失败</option><option value="partial">部分完成</option><option value="succeeded">成功</option></select></Field><Field label="观察到什么"><input required {...value('result')}/></Field></div><Field label="做错了什么（没有则留空）"><textarea rows={2} {...value('mistake')}/></Field>{f.mistake&&<><Check {...check('mistakeConfirmed')}>已有依据确认这是错误，不只是怀疑</Check><Field label="对应的纠正尝试（可选）"><select {...value('correction_id')}><option value="">尚未记录纠正操作</option>{records.filter(m=>m.kind==='attempt'&&m.id!==initial?.id).map(m=><option key={m.id} value={m.id}>{m.claim}</option>)}</select></Field></>}</>}
  {f.kind==='state'&&<><Field label="这是谁的实施进度"><select {...value('subject_id')}><option value="">整个项目</option>{records.filter(m=>['task','constraint','decision','goal'].includes(m.kind)||m.id===f.subject_id).map(m=><option key={m.id} value={m.id}>{m.claim}</option>)}</select></Field><Field label="当前进度"><select {...value('stage')}><option value="not_started">尚未开始</option><option value="in_progress">进行中</option><option value="blocked">遇到阻碍</option><option value="awaiting_validation">等待验证</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select></Field><Field label="下一步"><input {...value('next')}/></Field></>}
  <Field label="原始依据"><textarea required rows={3} placeholder="粘贴已去除隐私的原话、检查结果或操作记录" {...value('source')}/></Field>
  <div className="two"><Field label="依据来自谁"><select {...value('sourceKind')} onChange={e=>set({...f,sourceKind:e.target.value,confirmed:false})}><option value="human">用户原话</option><option value="agent">AI 的回答或整理</option><option value="tool">工具检查结果</option></select></Field>{f.sourceKind!=='human'&&<Field label="来源名称"><input required placeholder="例如 Codex 或测试工具" {...value('sourceName')}/></Field>}</div>
  <Check {...check('redacted')}>这份依据已经脱敏或删减</Check>
  <Check checked={f.inference} onChange={e=>set({...f,inference:e.target.checked,confirmed:false})}>这条内容仍然是推测</Check>
  {['decision','constraint'].includes(f.kind)&&<Check {...check('confirmed')} disabled={f.sourceKind!=='human'||f.inference}>这是我的明确决定 / 要求，依据中包含我的确认</Check>}
  <Check {...check('checked')}>已有核查结果</Check>
  {f.checked&&<><div className="two"><Field label="谁做了核查"><select {...value('checkerKind')}><option value="human">用户</option><option value="agent">AI</option><option value="tool">工具</option></select></Field>{f.checkerKind!=='human'&&<Field label="核查人或工具名称"><input required placeholder="例如 Codex 或测试工具" {...value('checkerName')}/></Field>}</div><p className="muted">核查结果不会自动变成用户确认。这里的身份由录入者填写。</p><Field label="核查说明"><textarea required rows={2} placeholder="检查了什么、结果如何、还有哪些范围没检查" {...value('checkNote')}/></Field></>}
  <div className="privacy-box"><Check {...check('reviewed')}>我已检查内容与依据，不含凭据或隐私</Check><small>本机规则只能识别部分敏感模式，不代替人工检查。</small>{issues.length>0&&<p role="alert" className="error">发现：{issues.join('、')}。请先移除原值，内容尚未保存。</p>}</div>
  <footer><button type="submit" className="primary" disabled={busy||!f.reviewed||issues.length>0}>{busy?'正在保存…':initial?'保存新版本':'保存记忆'}</button></footer>
 </form>;
}
