import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './ui.jsx';
import {originLabel} from '../shared/attribution.js';
const lifecycleLabel=value=>({accepted:'当前记录',proposed:'待确认记录',superseded:'已被替代',rejected:'已归档',retracted:'已撤回'})[value]||'状态未注明';

export default function StationHome({overview,loading,error,onRefresh,onProject,onStart,onReceive,onNew,onSearch,onResult,tools,mode='home',navigationBlocked=false}){
 const [query,setQuery]=useState(''),[results,setResults]=useState(null),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
 const requestId=useRef(0),currentQuery=useRef(query.trim());currentQuery.current=query.trim();
 useEffect(()=>{requestId.current++;setSearching(false);return()=>{requestId.current++;};},[mode]);
 function changeQuery(value){requestId.current++;currentQuery.current=value.trim();setQuery(value);setResults(null);setSearchError('');setSearching(false);}
 const projects=overview?.projects||[],pending=projects.filter(p=>p.inbox?.count||p.inbox?.error);
 const count=pending.reduce((n,p)=>n+(p.inbox?.count||0),0);
 async function search(e){e.preventDefault();if(navigationBlocked)return;const term=query.trim(),request=++requestId.current;setSearchError('');if(!term){setResults(null);setSearching(false);return;}setResults(null);setSearching(true);try{const value=await onSearch(term);if(request===requestId.current&&term===currentQuery.current)setResults(value);}catch(err){if(request===requestId.current&&term===currentQuery.current)setSearchError(err.message);}finally{if(request===requestId.current)setSearching(false);}}
 return <section className="station-home">
  <div className="topbar"><span>本机工作台</span><div className="actions"><button onClick={onRefresh} disabled={loading||navigationBlocked}>刷新</button><button className="primary" disabled={navigationBlocked} onClick={onNew}><Icon name="plus"/>新建项目</button></div></div>
  <div className="home-intro"><span className="eyebrow">PROJECT MEMORY</span><h1>{mode==='inbox'?'新记录都在这里':'换一个 AI，接着做'}</h1><p>{mode==='inbox'?'按项目检查 AI 送来的结果，保存后继续交接。':'工作留在原来的工具里，项目记忆在这里接续。'}</p></div>
  {error&&<div className="error banner home-error" role="alert"><span>{error}</span><button disabled={loading||navigationBlocked} onClick={onRefresh}>重新连接</button></div>}
  {loading&&!overview?<p>正在整理本机项目…</p>:<>
  {mode==='home'&&<>
   {projects.length===0&&<section className="first-project"><h2>从你的第一个项目开始</h2><p>以后换 AI，项目背景和试错记录会跟着你。</p><ol><li>选择项目文件夹</li><li>选择常用 AI</li><li>复制交接，在原 AI 中继续</li></ol><button className="primary" disabled={navigationBlocked} onClick={onNew}>连接第一个项目<Icon name="arrow"/></button></section>}
   {projects.length>0&&<form className="global-search" onSubmit={search}><Icon name="search"/><input aria-label="搜索所有项目记忆" placeholder="找一个决定、配置，或之前踩过的坑" value={query} maxLength={200} disabled={navigationBlocked} onChange={e=>changeQuery(e.target.value)}/><button disabled={searching||navigationBlocked} type="submit">{searching?'查找中…':'搜索记忆'}</button></form>}
   {searchError&&<p role="alert" className="error">{searchError}</p>}
   {results&&<section className="search-results"><div className="section-heading"><h2>找到 {results.total} 条记忆{results.total>results.results.length?'，显示前 '+results.results.length+' 条':''}</h2><button className="text-button" onClick={()=>changeQuery('')}>收起搜索</button></div>{results.results.length?results.results.map(r=><button key={JSON.stringify([r.projectId,r.id])} disabled={navigationBlocked} className="search-result" onClick={()=>onResult(r.projectId,r.id)}><div><span>{r.projectName} · {r.kindLabel} · {lifecycleLabel(r.lifecycle)} · {originLabel(r.origin)}</span><strong>{r.title}</strong><p>{r.snippet}</p></div><Icon name="arrow"/></button>):<p className="muted">没有找到匹配的已保存记忆，可以换一个词。草稿需先在新记录中检查。</p>}</section>}
   {projects.length>0&&<div className="home-stats"><div><strong>{projects.length}</strong><span>个项目</span></div><div><strong>{count}</strong><span>条待检查新记录</span></div><div><strong>{projects.reduce((n,p)=>n+p.needsReview,0)}</strong><span>条冲突或待复核</span></div><p>资料留在本机<br/>原始依据随记忆保留</p></div>}
  </>}
  {(pending.length>0||mode==='inbox')&&<section className="inbox-section"><div className="section-heading"><h2>待检查的新记录 <span className="count-badge">{count}</span></h2><span className="muted">保存不等于确认内容正确</span></div>{pending.length?pending.map(p=><article className="inbox-row" key={p.id}><div className="inbox-icon"><Icon name="inbox"/></div><div className="inbox-description"><strong>{p.name}</strong><p>{p.inbox.error||`${p.inbox.agent} 送来 ${p.inbox.count} 条记录`}</p>{p.inbox.titles?.length>0&&<span>{p.inbox.titles.slice(0,2).join(' · ')}</span>}</div><button className="primary" disabled={navigationBlocked} onClick={()=>onReceive(p.id)}>查看新记录<Icon name="arrow" size={16}/></button></article>):<div className="home-empty"><Icon name="inbox" size={30}/><h3>暂时没有新记录</h3><p>从项目卡片点“切换 AI”。AI 送回的记录会自动出现在这里，不必反复刷新。</p></div>}</section>}
  {mode==='home'&&projects.length>0&&<>
   <section><div className="section-heading"><h2>我的项目</h2><span className="muted">选一个项目，交给下一位 AI</span></div><div className="project-grid">{projects.map(p=><article className="project-card" key={p.id}><div className="project-card-heading"><span className="project-symbol"><Icon name="folder" size={23}/></span>{p.inbox?.count>0?<span className="count-badge">{p.inbox.count} 条新记录</span>:<span className="muted">{p.count} 条记忆</span>}</div><h3>{p.name}</h3><p className="project-goal">{p.goal||'还没有项目目标，可先连接文件夹或新增一条目标。'}</p>{p.goal&&<span className="muted goal-origin">{p.goalOrigin==='inference'?'目标来自 AI 整理，待核对':p.goalOrigin==='observation'?'目标来自观察记录，待核对':'目标来自用户陈述'}</span>}<div className="project-latest"><span>最近记录</span><p>{p.latest?.title||'等你留下第一条项目记忆'}</p></div><footer><button className="text-button" disabled={navigationBlocked} onClick={()=>onProject(p.id)}>查看记忆</button><button className="primary" disabled={navigationBlocked} onClick={()=>onStart(p.id)}>切换 AI<Icon name="arrow" size={17}/></button></footer></article>)}<button className="project-card new-project-card" disabled={navigationBlocked} onClick={onNew}><Icon name="plus" size={30}/><strong>加入一个项目</strong><span>从目标或已有文件开始</span></button></div></section>
   {(tools?.radar?.configured||tools?.website?.configured)&&<section className="local-tools"><div className="section-heading"><h2>常用工作台</h2><span className="muted">本机入口</span></div><div className="tool-grid">{[['radar','观察仓库','继续收集信号、整理机会卡'],['website','个人网站','查看作品与制作工具']].map(([id,title,description])=>{const tool=tools?.[id];return <article className="tool-card" key={id}><Icon name={id==='radar'?'radar':'globe'} size={26}/><div><h3>{title}</h3><p>{description}</p><small>{tool?.message||'正在检查本机入口…'}</small></div>{tool?.status==='ready'?<a className="button" href={tool.url} target="_blank" rel="noreferrer">打开<Icon name="arrow" size={16}/></a>:<span className="muted">{tool?.status==='unconfigured'?'待连接':'未就绪'}</span>}</article>;})}</div><p className="muted">两个工具继续使用原来的本机地址，原有浏览器记录保留在原地址。以后打开记忆站应用即可一起打开。</p></section>}
  </>}
  </>}
 </section>;
}
