import test from 'node:test';import assert from 'node:assert/strict';
import {createBundle,appendMemory,reviewMemory} from './core.mjs';
import {briefMemory,recallMemory,inspectMemory,agentBrief} from './recall.mjs';
import {runCLI} from '../memory.mjs';
function fixture(){const a=createBundle('合成贪吃蛇','');a.revision=4;const add=(kind,title,detail,extra={})=>appendMemory(a,{kind,title,detail,source:'原始依据：'+title+'。尾部原文标记',reviewed:true,...extra});
 const rule=add('constraint','保持离线运行','不依赖网络',{confirmed:true});rule.scope.condition='仅本地单人模式';
 const phone=add('fact','触屏按钮位置','手机操作使用底部按钮'),score=add('fact','计分规则','得分每次增加一分');
 const attempt=add('attempt','手机按钮失败尝试','按钮覆盖画面',{conditions:'竖屏',result:'遮住地图',outcome:'failed'});
 phone.related_ids=[attempt.id];
 for(let i=0;i<25;i++)add('fact','配色历史 '+i,'颜色讨论。'.repeat(100));return{a,rule,phone,score,attempt,add};}
test('不同任务返回不同线索，失败尝试可查，基础约束原条件不丢',()=>{const{a,rule,phone,score,attempt}=fixture(),before=JSON.stringify(a);const mobile=recallMemory(a,{task:'修改 mobile 操作',revision:4}),scoring=recallMemory(a,{task:'修改 scoring 规则',revision:4});assert.ok(mobile.records.some(x=>x.memory_id===phone.id));assert.ok(mobile.records.some(x=>x.memory_id===attempt.id));assert.ok(!mobile.records.some(x=>x.memory_id===score.id));assert.ok(scoring.records.some(x=>x.memory_id===score.id));const brief=briefMemory(a);assert.match(brief,/不依赖网络/);assert.match(brief,/仅本地单人模式/);assert.match(brief,/不是全部历史/);assert.ok(!brief.includes('尾部原文标记'));assert.ok(brief.length<5000);assert.equal(JSON.stringify(a),before);});
test('分页只返回六条，没命中不伪装相关，历史仍可被搜索',()=>{const{a,score}=fixture();score.lifecycle='rejected';const p=recallMemory(a,{task:'配色',revision:4});assert.equal(p.records.length,6);assert.equal(p.nextOffset,6);const next=recallMemory(a,{task:'配色',revision:4,offset:6});assert.ok(next.records.every(x=>!p.records.some(y=>y.memory_id===x.memory_id)));assert.equal(recallMemory(a,{task:'zzzzunknown',revision:4}).records.length,0);assert.ok(recallMemory(a,{task:'计分',revision:4}).records[0].preview.includes('历史'));});
test('查旧记录带出直接替代与冲突，关联不无限展开，原依据逐字保留',()=>{const{a,phone,score,attempt,add}=fixture();const newer=add('fact','新版触屏布局','两侧按钮',{replaces:phone.id});reviewMemory(a,newer.id,'conflict',score.id);const first=inspectMemory(a,{ids:[phone.id],revision:4});assert.ok(first.records.some(x=>x.memory.id===newer.id));assert.ok(!first.records.some(x=>x.memory.id===attempt.id));assert.ok(first.records.find(x=>x.memory.id===phone.id).unexpandedRelatedIds.includes(attempt.id));const second=inspectMemory(a,{ids:[newer.id],revision:4});assert.ok(second.records.some(x=>x.memory.id===score.id));for(const e of second.evidence)assert.equal(e.original,a.snapshots[e.source.snapshot.path]);});
test('拒绝旧版本、跨项目编号、重复编号和敏感查询；失败不修改档案',async()=>{const{a,phone}=fixture(),before=JSON.stringify(a);for(const f of [()=>recallMemory(a,{task:'手机',revision:3}),()=>inspectMemory(a,{ids:[phone.id],revision:3}),()=>inspectMemory(a,{ids:['unknown'],revision:4}),()=>inspectMemory(a,{ids:[phone.id,phone.id],revision:4}),()=>recallMemory(a,{task:'password: synthetic-secret',revision:4})])assert.throws(f);let calls=0;await assert.rejects(runCLI(['recall',a.bundle.project.id,'--revision','4','password: synthetic-secret'],{request:async()=>{calls++;return a;}}));assert.equal(calls,0);assert.equal(JSON.stringify(a),before);});
test('CLI 三步均只GET同项目保存档案，返回编号可继续读取，保留完整备用',async()=>{const{a,phone}=fixture(),calls=[];const request=async p=>{calls.push(p.pathname);return a;},id=a.bundle.project.id;const brief=await runCLI(['brief',id],{request,env:{}});assert.match(brief.output,/--revision 4/);const found=JSON.parse((await runCLI(['recall',id,'--revision','4','手机'],{request,env:{}})).output);assert.ok(found.records.length);const detail=JSON.parse((await runCLI(['inspect',id,'--revision','4',phone.id],{request,env:{}})).output);assert.match(detail.evidence[0].original,/尾部原文标记/);assert.deepEqual(calls,Array(3).fill('/api/projects/'+id));assert.match(agentBrief(a),/context .* --full/);});
test('再长的原文不进入简报，但确认要求与核验边界仍然保留',()=>{const{a,rule,add}=fixture();add('fact','冗长历史','历史'.repeat(5000));rule.freshness.status='stale';rule.freshness.reason='条件变化';const brief=briefMemory(a);assert.match(brief,/stale/);assert.match(brief,/不依赖网络/);assert.match(brief,/不.*验收/);assert.ok(brief.length<6000);});
