import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {once} from 'node:events';import {fileURLToPath} from 'node:url';
import {createBundle,validateArchive} from './core.mjs';import {createInbox} from './inbox.mjs';import {createBridge} from './bridge.mjs';
test('真实保存入口原子处理收尾，失败不消耗草稿；版本冲突和跨任务被拒绝',{timeout:15000},async t=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'outcome-http-')),stationRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),archive=createBundle('合成收尾接口',''),id=archive.bundle.project.id;
 const sock=net.createServer();await new Promise(r=>sock.listen(0,'127.0.0.1',r));const port=sock.address().port;await new Promise(r=>sock.close(r));
 fs.mkdirSync(path.join(data,id));const file=path.join(data,id,'project.json');fs.writeFileSync(file,JSON.stringify(archive));const inbox=createInbox({directory:path.join(data,'inbox'),loadArchive:()=>archive}),bridge=createBridge({directory:path.join(data,'bridges'),port,stationRoot,loadArchive:()=>archive,inbox});
 const ticket=bridge.prepare(id,{target:'codex',revision:0,task:'核对合成结果',taskMode:'new'}).ticket;bridge.receipt(id,ticket.id,{revision:0,taskReceived:true});
 const worklog={format:'project-memory-worklog',version:'0.1',project_id:id,session:{id:'close-http',agent:'Codex AI',actor:{kind:'agent',id:'Codex AI'},handoff_id:ticket.id},entries:[{id:'one',kind:'fact',title:'合成结果',detail:'合成检查通过。',origin:'observation',source:{speaker:{kind:'agent',id:'Codex AI'},text:'原始合成观察保留。'}}]};
 const draft=inbox.stage(archive,{sourceReviewed:true,worklog}),original=fs.readFileSync(file,'utf8');
 const child=spawn(process.execPath,[path.join(stationRoot,'server/index.mjs')],{env:{...process.env,MEMORY_STATION_PORT:String(port),MEMORY_STATION_DATA_DIR:data,MEMORY_STATION_EMPTY:'1'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{if(child.exitCode===null){const end=once(child,'exit');child.kill();await end;}fs.rmSync(data,{recursive:true,force:true});});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('start timeout')),5000);child.once('error',reject);child.stdout.on('data',b=>{if(b.toString().includes('记忆站：http')){clearTimeout(timer);resolve();}});child.once('exit',()=>{clearTimeout(timer);reject(Error('server exited'));});});
 const call=async(p,body)=>{const r=await fetch(`http://127.0.0.1:${port}/api${p}`,body?{method:'POST',headers:{'Content-Type':'application/json','X-Memory-Station':'1'},body:JSON.stringify(body)}:{});return {status:r.status,body:await r.json()};};
 const choice={ticket_id:ticket.id,stage:'completed',next:'',confirmed:true},input={revision:0,worklog,selected_ids:['one'],associate_task:true,reviewed:true,reviewer:{kind:'human',id:'synthetic-user'},draftId:draft.id,andHandoff:true,handoffReviewed:true,task_outcome:choice};
 for(const change of [{task_outcome:{...choice,confirmed:false}},{associate_task:false},{reviewer:{kind:'agent',id:'synthetic-agent'}},{revision:9},{task_outcome:{...choice,ticket_id:id}}]){
  const r=await call(`/projects/${id}/work-import`,{...input,...change});assert.notEqual(r.status,200);assert.equal(fs.readFileSync(file,'utf8'),original);assert.equal((await call(`/projects/${id}/inbox`)).body.draft.id,draft.id);
 }
 const saved=await call(`/projects/${id}/work-import`,input);assert.equal(saved.status,200,JSON.stringify(saved.body));const a=saved.body.archive;assert.equal(a.revision,1);assert.equal(a.task_outcomes.length,1);assert.equal(a.bundle.memories[0].verification.status,'unverified');assert.equal(a.bundle.memories[0].by.kind,'agent');assert.ok(Object.values(a.snapshots).includes('原始合成观察保留。'));assert.equal((await call(`/projects/${id}/inbox`)).body.draft,null);
 const outcome={...choice,reviewer:input.reviewer};assert.equal((await call(`/projects/${id}/task-outcome`,{...outcome,revision:0,stage:'in_progress'})).status,409);
 const reopened=await call(`/projects/${id}/task-outcome`,{...outcome,revision:1,stage:'in_progress',next:'继续核对手机'});assert.equal(reopened.status,200);assert.deepEqual(reopened.body.archive.bundle,a.bundle);assert.deepEqual(reopened.body.archive.snapshots,a.snapshots);assert.equal(reopened.body.archive.task_outcomes.length,2);
 const restored=await call('/import',{reviewed:true,archive:reopened.body.archive});assert.equal(restored.status,201,JSON.stringify(restored.body));validateArchive(restored.body);assert.notEqual(restored.body.bundle.project.id,id);assert.equal(restored.body.task_outcomes[0].project_id,restored.body.bundle.project.id);
 const history=(await call(`/projects/${restored.body.bundle.project.id}/bridge`)).body.taskHistory;assert.equal(history.length,1);assert.equal(history[0].historyOnly,true);assert.equal(history[0].outcome.next,'继续核对手机');
});
