import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createBundle,validateArchive} from './core.mjs';import {createBridge} from './bridge.mjs';import {createInbox} from './inbox.mjs';import {importWorklog,previewWorklog} from './worklog.mjs';import {taskWorkGroups} from '../shared/work-association.js';
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'work-association-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));let archive=createBundle('合成项目','');const id=archive.bundle.project.id;const inbox=createInbox({loadArchive:()=>archive});const bridge=createBridge({directory:root,port:4180,stationRoot:path.resolve('.'),loadArchive:()=>archive,inbox,workspace:{get:()=>({binding:null})}});return {id,bridge,inbox,get archive(){return archive;},save(a){archive=a;},task(text='任务甲'){const ticket=bridge.prepare(id,{target:'codex',revision:archive.revision,task:text,taskMode:'new'}).ticket;bridge.receipt(id,ticket.id,{revision:archive.revision,taskReceived:true});return ticket;}};}
const work=(f,ticket)=>({format:'project-memory-worklog',version:'0.1',project_id:f.id,session:{id:'synthetic-result',agent:'Codex',actor:{kind:'agent',id:'Codex'},...(ticket?{handoff_id:ticket.id}:{})},entries:[{id:'one',kind:'fact',title:'本次结果',detail:'合成观察：完成局部修改，其他未验证。',origin:'observation',source:{speaker:{kind:'agent',id:'Codex'},text:'合成AI原文：只修改了局部，未验证其他。'}}]});
const save=(f,w,associate=true)=>importWorklog(f.archive,{worklog:w,reviewed:true,selected_ids:['one'],associate_task:associate},{association:f.bridge.workAssociation(f.id,w)});
test('旧任务晚回结果仍归旧任务；读取编号进入交接格式，当前任务不被替换',t=>{const f=setup(t),a=f.task(),context=f.bridge.context(f.id,a.id);assert.match(context.context,/handoff_id/);const b=f.task('任务乙'),w=work(f,a),r=save(f,w);assert.equal(r.work_task_link.task_id,a.taskThreadId);assert.equal(taskWorkGroups(r.archive)[0].task,'任务甲');assert.equal(f.bridge.status(f.id).activeTask.id,b.id);assert.equal(r.archive.snapshots[r.archive.bundle.evidence[0].snapshot.path],w.entries[0].source.text);assert.equal(r.archive.bundle.memories[0].approval,undefined);});
test('缺编号、错误编号、没有读取回执与整理者不符都不按最近任务归类',t=>{const f=setup(t),a=f.task();for(const mutate of [w=>delete w.session.handoff_id,w=>w.session.handoff_id='00000000-0000-4000-8000-000000000000',w=>w.session.actor.id='Other']){const w=work(f,a);mutate(w);assert.equal(f.bridge.workAssociation(f.id,w).status,'unknown');assert.throws(()=>save(f,w),/归属/);assert.equal(taskWorkGroups(save(f,w,false).archive).length,0);}const unread=f.bridge.prepare(f.id,{target:'codex',revision:0,task:'未读取任务',taskMode:'new'}).ticket;assert.equal(f.bridge.workAssociation(f.id,work(f,unread)).status,'unknown');});
test('跨项目编号不能关联，格式错误不会进入待检查区',t=>{const f=setup(t),g=setup(t),other=g.task();const w=work(f,other);assert.equal(f.bridge.workAssociation(f.id,w).status,'unknown');w.session.handoff_id='wrong';assert.throws(()=>previewWorklog(f.archive,w),/格式/);assert.throws(()=>f.inbox.stage(f.archive,{sourceReviewed:true,worklog:w}),/格式/);});
test('可暂不归类；重复保存不新增索引或改变先前归类',t=>{const f=setup(t),a=f.task(),w=work(f,a),r=save(f,w,false);f.save(r.archive);assert.equal(taskWorkGroups(f.archive).length,0);const again=save(f,w,true);assert.equal(again.added,0);assert.equal(taskWorkGroups(again.archive).length,0);});
test('只有实际保存过的对应工作能显式继续旧任务，不继承新任务编号',t=>{const f=setup(t),a=f.task();f.task('任务乙');const w=work(f,a);assert.throws(()=>f.bridge.prepare(f.id,{target:'claude',revision:0,task:a.task,taskMode:'continue',continuesTicketId:a.id,resumeWorkSession:w.session.id}),/关联无法核对/);f.save(save(f,w).archive);const next=f.bridge.prepare(f.id,{target:'claude',revision:0,task:a.task,taskMode:'continue',continuesTicketId:a.id,resumeWorkSession:w.session.id}).ticket;assert.equal(next.taskThreadId,a.taskThreadId);assert.equal(next.task,'任务甲');assert.throws(()=>f.bridge.prepare(f.id,{target:'claude',revision:0,task:'偷偷改目标',taskMode:'continue',continuesTicketId:a.id,resumeWorkSession:w.session.id}),/沿用原任务/);});
test('任务索引随档案保留，篡改结构被拒绝，导入到其他项目不冒充本地任务',t=>{const f=setup(t),a=f.task(),r=save(f,work(f,a)).archive;validateArchive(r);const copy=structuredClone(r);copy.bundle.project.id='00000000-0000-4000-8000-000000000000';assert.equal(taskWorkGroups(copy).length,0);r.work_imports[0].task_link.ticket_id='../wrong';assert.throws(()=>validateArchive(r),/归属/);});
test('Codex AI 署名按原交接归类，混用已知别名不改变原始身份与依据',t=>{const f=setup(t),a=f.task(),w=work(f,a);w.session.agent='Codex AI';w.session.actor.id='Codex AI';w.entries[0].source.speaker.id='Codex AI';const original=JSON.stringify(w);f.task('较新的其他任务');const r=save(f,w);assert.equal(r.work_task_link.ticket_id,a.id);assert.equal(r.archive.bundle.memories[0].by.id,'Codex AI');assert.equal(r.archive.snapshots[r.archive.bundle.evidence[0].snapshot.path],w.entries[0].source.text);assert.equal(JSON.stringify(w),original);w.session.actor.id='Codex';assert.equal(f.bridge.workAssociation(f.id,w).status,'matched');});
test('别名不能跨 AI、身份种类或未知名称匹配，也不能跳过读取与项目检查',t=>{const f=setup(t),a=f.task();for(const [agent,id,kind] of [['Claude Code','Claude Code','agent'],['Codex AI','Claude Code AI','agent'],['Codex AI','Codex AI','human'],['Codex AI','Codex AI','tool'],['My Codex AI','My Codex AI','agent'],['Codex AI helper','Codex AI helper','agent']]){const w=work(f,a);Object.assign(w.session,{agent,actor:{id,kind}});assert.equal(f.bridge.workAssociation(f.id,w).status,'unknown');}const w=work(f,a);w.session.agent=w.session.actor.id='Codex AI';delete w.session.handoff_id;assert.equal(f.bridge.workAssociation(f.id,w).status,'unknown');});
